#!/bin/zsh

SCREEN_DRAW=/home/leake/.cargo/bin/screen-draw
my_pid=$$

# Start by switching to the special workspace and firing up screen_draw
hyprctl eval "hl.exec_cmd(\"$SCREEN_DRAW\", { workspace = \"special:screen_draw\" })"
hyprctl dispatch 'hl.dsp.workspace.toggle_special("screen_draw")'
sc_pid=$(pgrep -x screen-draw)

# Bind F9 to turn on/off screen_draw + the workspace
hyprctl eval "hl.bind(\"F9\", hl.dsp.workspace.toggle_special(\"screen_draw\"))"

# Bind Alt F9 to send SIGTERM to this script
hyprctl eval "hl.bind(\"ALT + F9\", function() hl.exec_cmd(\"kill -15 $my_pid\") end)"

# Run this on cleanup
wait_pid=$my_pid
cleanup() {
    echo "Performing cleanup tasks..."
    hyprctl eval "hl.unbind(\"F9\")"
    hyprctl eval "hl.unbind(\"ALT + F9\")"
    kill -15 $wait_pid
    kill -15 $sc_pid
    exit 0
}

trap cleanup SIGTERM SIGINT

# Wait until we get the signal to cleanup
sleep inf &
wait_pid=$!
wait $wait_pid
