#!/bin/bash

BASE_PATH=~/.config/hypr/waybar
LAYOUT=$(for a in $(ls $BASE_PATH/configs); do echo -en "$a\n" ; done | rofi -config ~/.config/rofi/simple_menu.rasi -dmenu)
ln -srf $BASE_PATH/configs/$LAYOUT $BASE_PATH/config
ln -srf $BASE_PATH/styles/$LAYOUT.css $BASE_PATH/style.css
touch -h $BASE_PATH/config
